#!/usr/bin/env node
<!--startLayout "skeleton@common"-->
<!--setBlock "title" as "welcome"-->
<!--setBlock "charset" as "UTF-8"-->
<!--startBlock "content"-->
  <!--useWidget "a" with {a: a, b: b}-->

<!--endBlock "content" -->
<div></div>
<!--endLayout "skeleton@common"-->